export default function AboutOXARC() {
  const locations = ['Bend, OR','Boise, ID','Coeur d’Alene, ID','Colville, WA','Ellensburg, WA','Hermiston, OR','La Grande, OR','Lewiston, ID','Moses Lake, WA','Nampa, ID','Okanogan, WA','Pasco, WA','Portland, OR','Sandpoint, ID','Spokane, WA','Springfield, WA','Sunnyside, WA','The Dalles, OR','Twin Falls, ID','Walla Walla, WA','Wenatchee, WA','Yakima, WA'];
  return <main className="about-page">
    <div className="utility"><span>Serving the Inland & Pacific Northwest</span><span>Need help? <b>1-800-765-9055</b></span></div>
    <header className="about-header"><a className="brand" href="../"><img className="oxarc-logo" src="../oxarc-logo.png" alt="OXARC"/><small>Part of Meritus Gas Partners</small></a><nav className="about-nav"><a href="../">Shop products</a><a href="#capabilities">Capabilities</a><a href="#locations">Locations</a><a className="contact-link" href="https://meritusgas.com/contact-us/?selected-partner=5805" target="_blank" rel="noreferrer">Contact OXARC</a></nav></header>
    <section className="about-hero"><div><span className="kicker">ABOUT OXARC</span><h1>Northwest industry has counted on OXARC since 1968.</h1><p>OXARC is a single-source supplier of welding equipment and consumables, industrial and specialty gases, safety supplies, fire and life-safety solutions, and essential services for demanding operations.</p><div className="about-hero-actions"><a href="../">Shop the catalog</a><a href="https://meritusgas.com/partners/oxarc/locations/" target="_blank" rel="noreferrer">Find a location</a></div></div><aside><strong>56+ years</strong><span>Serving the Northwestern United States</span><strong>22 regional markets</strong><span>Across Washington, Oregon and Idaho</span><strong>Local delivery fleet</strong><span>Supporting efficient and just-in-time fulfillment</span></aside></section>
    <section className="company-story"><div><span className="kicker">WHO WE ARE</span><h2>Local service backed by regional strength</h2></div><div><p>OXARC serves a broad range of industries with practical, cost-effective products and services designed to keep facilities safe, productive and supplied. Customers receive individualized attention from local specialists along with access to extensive inventory, technical knowledge and leading manufacturing brands.</p><p>Stores, warehouses and distribution centers throughout the region are connected by OXARC&apos;s own trucking network. That infrastructure supports dependable delivery, streamlined inventory management and responsive service when operations cannot wait.</p><p>As part of Meritus Gas Partners, OXARC combines the relationships and accountability of a locally operated distributor with the technology and resources of a growing national network.</p></div></section>
    <section className="capability-section" id="capabilities"><div className="about-section-heading"><span className="kicker">PRODUCTS & SERVICES</span><h2>One partner for critical industrial needs</h2><p>Experienced professionals help customers evaluate requirements, choose the right products and build solutions around the way their operations actually work.</p></div><div className="capability-grid"><article><span>01</span><h3>Welding & industrial supplies</h3><p>Welding machines, robotics and automation, filler metals, abrasives, cutting equipment, hand tools, accessories and repair support.</p></article><article><span>02</span><h3>Industrial & specialty gases</h3><p>High-purity industrial, medical and specialty gases, welding mixtures, cylinders and chemical solutions supported by regional distribution.</p></article><article><span>03</span><h3>Safety products & services</h3><p>PPE, jobsite safety products, new safety technologies and practical guidance related to changing regulatory requirements.</p></article><article><span>04</span><h3>CO₂, beverage & dry ice</h3><p>Carbon-dioxide systems, beverage-gas programs and dry-ice solutions for food, beverage and commercial applications.</p></article><article><span>05</span><h3>Fire & life safety</h3><p>Fire extinguishers, first-aid products, inspection and service, suppression systems for businesses and vehicles, and fire-alarm solutions.</p></article><article><span>06</span><h3>Training & technical expertise</h3><p>Job-focused welder training, inspection and testing capabilities, factory representation and factory-trained service technicians.</p></article></div></section>
    <section className="service-promise"><div><span className="kicker">WHY OXARC</span><h2>Built around uptime, safety and responsive service</h2></div><ul><li><b>Experienced local specialists</b><span>Product knowledge and personalized recommendations for real-world applications.</span></li><li><b>Broad, dependable inventory</b><span>Retail and wholesale products from established industrial manufacturers.</span></li><li><b>Regional distribution</b><span>Warehouses, stock points and a proprietary fleet supporting efficient delivery.</span></li><li><b>Service after the sale</b><span>Warranty repair, emergency repair and ongoing support for supplied equipment.</span></li></ul></section>
    <section className="location-section" id="locations"><div className="about-section-heading"><span className="kicker">REGIONAL PRESENCE</span><h2>Serving communities across the Northwest</h2><p>OXARC locations span Washington, Oregon and Idaho, bringing inventory and expertise closer to the customers who rely on it.</p></div><div className="location-list">{locations.map(location=><span key={location}>{location}</span>)}</div><a className="location-cta" href="https://meritusgas.com/partners/oxarc/locations/" target="_blank" rel="noreferrer">View location details</a></section>
    <section className="about-final"><div><span className="kicker">READY TO GET TO WORK?</span><h2>Find the products you need or connect with a local OXARC specialist.</h2></div><div><a href="../">Shop products</a><a href="https://meritusgas.com/contact-us/?selected-partner=5805" target="_blank" rel="noreferrer">Contact OXARC</a></div></section>
  </main>;
}
